### ISSUE TITLE
 [mac-크롬] 회원가입 안됨

### ISSUE THREAD

**Issue by from-minju** [100-hours-a-week/2-yeoni-lee-community-issue#11]
**버그 설명**
이전에는 회원가입이 되었는데 다시 회원가입을 하려니
정보를 알맞게 입력했는데도 회원가입이 안됨.
<img width="1870" alt="image" src="https://github.com/user-attachments/assets/2194c9dc-62c8-40e0-8f5a-c2daf6a5d15a" />

**Comment by juyeon320** [comment]
(한글 인코딩 문제라면... )
수정 완!
