### ISSUE TITLE
 [macOS-크롬-내정보수정] 이미지 입력폼이 두번 뜨는 오류

### ISSUE THREAD

**Issue by mingoo36** [100-hours-a-week/2-yeoni-lee-community-issue#12]
**버그 설명**
프로필 사진을 변경하려고 이미지를 선택하고 확인을 누르면 한번더 입력폼이 뜨는 오류발생

**재현하는 방법**
동작을 재현하는 단계:
1. 내정보 수정으로 이동
2. 파일선택
3. 이미지 선택후 확인
4. 또 이미지 입력폼이 열림

**스크린샷**
![image](https://github.com/user-attachments/assets/42f11b7c-b21e-4ccb-a85e-c2bfdba8f57f)

**Comment by juyeon320** [comment]
수정 완!
