### ISSUE TITLE
 [MAC-크롬 브라우저-전체화면-회원가입] 닉네임 공백 입력 가능

### ISSUE THREAD

**Issue by miginho12** [100-hours-a-week/2-yeoni-lee-community-issue#3]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

회원가입 시 닉네임을 없이도 생성이 가능 + 제목과 내용도 공백이 가능

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
<img width="601" alt="image" src="https://github.com/user-attachments/assets/167bf6cc-b735-425b-9906-e77ff7bb6808" />
<img width="528" alt="image" src="https://github.com/user-attachments/assets/37225af1-8469-4646-8c68-240050c0fd61" />

->

게시글 오류
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/e9037c27-6231-4235-af44-41e9052695b9" />

**Comment by juyeon320** [comment]
수정 반쯤 완..!
