### ISSUE TITLE
 [MAC-크롬 브라우저-전체화면-게시물 목록] 시간 포맷

### ISSUE THREAD

**Issue by miginho12** [100-hours-a-week/2-yeoni-lee-community-issue#7]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.
시간 포맷 수정 필요해보입니다.

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
<img width="517" alt="image" src="https://github.com/user-attachments/assets/09d6f554-a547-465e-9798-247336b8dfbc" />

**Comment by juyeon320** [comment]
수정 완!
