### ISSUE TITLE
 [macOS-크롬] 게시글 작성 오류

### ISSUE THREAD

**Issue by mingoo36** [100-hours-a-week/2-yeoni-lee-community-issue#8]
**버그 설명**
게시글 작성 안됨..

**스크린샷**
![image](https://github.com/user-attachments/assets/f5dc1e8f-ebd5-492f-9187-88ecfd937bed)

**Comment by juyeon320** [comment]
( 아마 한글 인코딩 문제라면.. )
수정 완!
