### ISSUE TITLE
ivan QA 진행

### ISSUE THREAD

**Issue by ingyulim** [100-hours-a-week/2-yeoni-lee-community-issue#9]
1. 본인 소유가 아닌 댓글, 게시글 수정,삭제 가능한 issue.

2. 닉네임 변경 후 기존 댓글의 댓글 작성자에 이전 닉네임이 뜸.
<img width="772" alt="image" src="https://github.com/user-attachments/assets/dc300289-0913-453b-b6be-fcb871ba6b8c" />

**Comment by juyeon320** [comment]
1.2 둘 다 해결 완!
